### PR TITLE
Truffle/Graal supports AOT

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by chrisseaton** [comment]
It doesn't support AOT of *Ruby* code though. Only AOT of the Java code that implements the interpreter. TruffleRuby is AOT compiled only in the sense that MRI is AOT compiled C code.

In the future TruffleRuby may be able to AOT Ruby code, but not today.

Does that make sense? Thanks for taking the time to suggest it though.

**Comment by ShalokShalom** [comment]
Interesting. The Graal documentation seems to suggest otherwise. 

From what I understood, is every language supported to be compiled into a native image, just because its compatible with the intermediate representation.

**Comment by chrisseaton** [comment]
It's a confusing subject to explain, because it's all working at several levels of indirection and meta-ness.

Could Graal literally take a Ruby graph and produce code for it AOT? Yes. Is that code going to be runnable in a later process? No that doesn't work yet because the environment won't match the code.

@eregon can you confirm my understanding?

**Comment by ShalokShalom** [comment]
One out of many examples. "GraalVM can produce native images from Ruby code" is all over the place in the documentation. 

Optionally is a bit confusing here, I guess this is either just a weird wording or it means the JVM related code is nessecary?

Screenshot_20220802-173632~2

**Comment by chrisseaton** [comment]
It produces a native image of the Ruby interpreter, which can include Ruby application code and state, but not machine code from the Ruby code, at the moment.

**Comment by ShalokShalom** [comment]
So that means it will not execute?

**Comment by eregon** [comment]
The TruffleRuby interpreter, which is written in Java, is compiled AOT to native code, as a native image. The Ruby code itself is currently never compiled AOT, but is always JIT compiled.

In the future there will be a way to cache the JIT compilation of Ruby code and reuse it across processes, that cache will be a separate file from the native image.

**Comment by chrisseaton** [comment]
> The Ruby code itself is currently never compiled AOT

Thanks will close based on that. Thanks for taking the time anyway @ShalokShalom to suggest a change - I really appreciate it.

**Comment by ShalokShalom** [comment]
Thanks a lot as well, this clearifies it. 

Just to be sure: Native image with Ruby is possible, its just that the Ruby code inside runs JIT then, not AOT. 

Cause I semi-understood that the lack of AOT also prevents native images.

**Comment by chrisseaton** [comment]
Yes, Ruby code runs in the interpreter and JIT when inside the native image.

**Pull request closed without merging**
